export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const LOGIN_ATTEMPT_STORE = Symbol('LOGIN_ATTEMPT_STORE');
export const PASSWORD_HANSHER = Symbol('PASSWORD_HANSHER');
export const ACCESS_TOKEN_ISSUER = Symbol('ACCESS_TOKEN_ISSUER');
