import { JwtService } from '@nestjs/jwt';
import { Test, type TestingModule } from '@nestjs/testing';

import { AppConfigModule } from '@/common/config/config.module';
import { JwtAccessTokenIssuerService } from './jwt-access-token-issuer.service';

describe('JwtAccessTokenIssuerService', () => {
  let service: JwtAccessTokenIssuerService;
  let jwtService: {
    signAsync: jest.Mock;
  };
  let configService: {
    getOrThrow: jest.Mock;
  };

  beforeEach(async () => {
    jwtService = {
      signAsync: jest.fn(),
    };
    configService = {
      getOrThrow: jest.fn(),
    };

    const module: TestingModule = await Test.createTestingModule({
      imports: [AppConfigModule],
      providers: [
        JwtAccessTokenIssuerService,
        {
          provide: JwtService,
          useValue: jwtService,
        },
      ],
    }).compile();

    service = module.get<JwtAccessTokenIssuerService>(JwtAccessTokenIssuerService);
  });

  describe('issue()', () => {
    it('should issue an access token successfully', async () => {
      jwtService.signAsync.mockResolvedValue('mock-access-token');
      configService.getOrThrow.mockResolvedValue(900);

      const result = await service.issue({
        userId: 'user-123',
      });

      expect(result).toEqual({
        accessToken: 'mock-access-token',
        expiresIn: 900,
      });
    });

    it('should use userId as JWT subject', async () => {
      jwtService.signAsync.mockResolvedValue('mock-access-token');

      await service.issue({
        userId: 'user-123',
      });

      expect(jwtService.signAsync).toHaveBeenCalledWith({
        sub: 'user-123',
      });
    });

    it('should call JwtService.signAsync exactly once', async () => {
      jwtService.signAsync.mockResolvedValue('mock-access-token');

      await service.issue({
        userId: 'user-123',
      });

      expect(jwtService.signAsync).toHaveBeenCalledTimes(1);
    });

    it('should return the token generated by JwtService', async () => {
      const accessToken = 'generated-jwt-token';

      jwtService.signAsync.mockResolvedValue(accessToken);

      const result = await service.issue({
        userId: 'user-123',
      });

      expect(result.accessToken).toBe(accessToken);
    });

    it('should propagate JwtService errors', async () => {
      const error = new Error('JWT signing failed');

      jwtService.signAsync.mockRejectedValue(error);

      await expect(
        service.issue({
          userId: 'user-123',
        }),
      ).rejects.toThrow('JWT signing failed');
    });
  });
});
