export enum HTTP_CLIENTS {
  AUTH = 'AUTH_HTTP_CLIENT',
  FACTORY = 'FACTORY_HTTP_CLIENT',
  TELEMETRY = 'TELEMETRY_HTTP_CLIENT',
}

export const HTTP_CLIENT_MODULE_OPTIONS = 'HTTP_CLIENT_MODULE_OPTIONS';
