export enum ErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  VALIDATION_ERROR = 'VALIDATION_ERROR',

  USER_NOT_FOUND = 'USER_NOT_FOUND',

  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',

  FACTORY_NOT_FOUND = 'FACTORY_NOT_FOUND',

  MACHINE_NOT_FOUND = 'MACHINE_NOT_FOUND',

  PERMISSION_DENIED = 'PERMISSION_DENIED',
}
