export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'AUTH_001',
  TOKEN_EXPIRED = 'AUTH_002',
  TOKEN_INVALID = 'AUTH_003',
  ACCESS_DENIED = 'AUTH_004',

  // User
  USER_NOT_FOUND = 'USER_001',
  USER_ALREADY_EXISTS = 'USER_002',

  // Factory
  FACTORY_NOT_FOUND = 'FAC_001',
  FACTORY_ACCESS_DENIED = 'FAC_002',

  // Machine
  MACHINE_NOT_FOUND = 'MAC_001',

  // System
  VALIDATION_ERROR = 'SYS_001',
  INTERNAL_ERROR = 'SYS_999',
}
