export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'AUTH_001',
  MISSING_TOKEN = 'AUTH_002',
  AUTH_BLOCKED = 'AUTH_003',
  TOKEN_EXPIRED = 'AUTH_004',
  TOKEN_INVALID = 'AUTH_005',
  ACCESS_DENIED = 'AUTH_006',
  SESSION_NOT_FOUND = 'AUTH_007',
  SESSION_REVOKED = 'AUTH_008',

  // User
  USER_NOT_FOUND = 'USER_001',
  USER_ALREADY_EXISTS = 'USER_002',

  // Factory
  FACTORY_NOT_FOUND = 'FAC_001',
  FACTORY_ACCESS_DENIED = 'FAC_002',

  // Machine
  MACHINE_NOT_FOUND = 'MAC_001',

  // System
  VALIDATION_ERROR = 'SYS_001',
  BAD_GATEWAY = 'SYS_002',
  INTERNAL_ERROR = 'SYS_999',
}
