export const USER_REPOSITORY_PORT = Symbol('USER_REPOSITORY_PORT');
export const LOGIN_ATTEMPT_STORE_PORT = Symbol('LOGIN_ATTEMPT_STORE_PORT');
export const SESSION_STORE_PORT = Symbol('SESSION_STORE_PORT');
export const ACCESS_TOKEN_SERVICE_PORT = Symbol('ACCESS_TOKEN_SERVICE_PORT');
export const PASSWORD_HASHER_PORT = Symbol('PASSWORD_HASHER_PORT');

export const LOGIN_SECURITY_CONFIG = Symbol('LOGIN_SECURITY_CONFIG');
