export const PASSWORD_HASHER_PORT = Symbol('PASSWORD_HASHER_PORT');
export const LOGIN_ATTEMPT_STORE_PORT = Symbol('LOGIN_ATTEMPT_STORE_PORT');
export const ACCESS_TOKEN_PORT = Symbol('ACCESS_TOKEN_PORT');
